# Pipeline do processo de seleção dos canais

## Snowball Sampling

### 1. Seleção manual dos canais iniciais (Snowball Sampling)

Canais iniciais obtidos nessa etapa:

|    | Canal                                      | arroba                         | ID                       | URL                                                      |
|----|--------------------------------------------|--------------------------------|--------------------------|----------------------------------------------------------|
|  1 | AlgaWorks                                  | @algaworks                     | UCIPQ0ZqTl5e5U2OFKENOh9g | https://www.youtube.com/channel/UCIPQ0ZqTl5e5U2OFKENOh9g |
|  2 | Alura                                      | @alura                         | UCo7EHzKF2zDFWszw7Dg4mPw | https://www.youtube.com/channel/UCo7EHzKF2zDFWszw7Dg4mPw |
|  3 | Asimov Academy                             | @AsimovAcademy                 | UCxXL5491Db9U8Rhfs-2LVFg | https://www.youtube.com/channel/UCxXL5491Db9U8Rhfs-2LVFg |
|  4 | balta.io                                   | @baltaio                       | UCgnACLvM9O5lfm9ZBh_d3cg | https://www.youtube.com/channel/UCgnACLvM9O5lfm9ZBh_d3cg |
|  5 | Bóson Treinamentos                         | @bosontreinamentos             | UCzOGJclZQvPVgYZIwERsf5g | https://www.youtube.com/channel/UCzOGJclZQvPVgYZIwERsf5g |
|  6 | DevClub \| Programação                     | @canaldevclub                  | UCmv3rI2yhyNdqy7GNt5e13A | https://www.youtube.com/channel/UCmv3rI2yhyNdqy7GNt5e13A |
|  7 | Canal DevPro                               | @canaldevpro                   | UCGjx62365UJ8XTWU_5GZC-g | https://www.youtube.com/channel/UCGjx62365UJ8XTWU_5GZC-g |
|  8 | CFBCursos                                  | @cfbcursos                     | UCqHIWCQSq0yeE-1nbcRnt2w | https://www.youtube.com/channel/UCqHIWCQSq0yeE-1nbcRnt2w |
|  9 | Cod3r Cursos                               | @cod3r                         | UCcMcmtNSSQECjKsJA1XH5MQ | https://www.youtube.com/channel/UCcMcmtNSSQECjKsJA1XH5MQ |
| 10 | Curso de tecnologia e programação          | @cursodetecnologiaeprogramação | UC-dRoABm-_rKxZG9m4wzR8w | https://www.youtube.com/channel/UC-dRoABm-_rKxZG9m4wzR8w |
| 11 | DevDojo                                    | @DevDojoBrasil                 | UCjF0OccBT05WxsJb2zNkL4g | https://www.youtube.com/channel/UCjF0OccBT05WxsJb2zNkL4g |
| 12 | DevMedia                                   | @devmedia.oficial              | UClBrpNsTEFLbZDDMW1xiOaQ | https://www.youtube.com/channel/UClBrpNsTEFLbZDDMW1xiOaQ |
| 13 | DevPleno                                   | @DevPleno                      | UC07JWf9A0B1scApbS1Te7Ww | https://www.youtube.com/channel/UC07JWf9A0B1scApbS1Te7Ww |
| 14 | Mario Souto - Dev Soutinho                 | @DevSoutinho                   | UCzR2u5RWXWjUh7CwLSvbitA | https://www.youtube.com/channel/UCzR2u5RWXWjUh7CwLSvbitA |
| 15 | Felipe Rocha • Full Stack Club             | @dicasparadevs                 | UC8TRfZVb-M_ivbU9yiocTvQ | https://www.youtube.com/channel/UC8TRfZVb-M_ivbU9yiocTvQ |
| 16 | Eduardo Mendes                             | @Dunossauro                    | UCAaKeg-BocRqphErdtIUFFw | https://www.youtube.com/channel/UCAaKeg-BocRqphErdtIUFFw |
| 17 | eadvideos                                  | @eadvideosoficial              | UC6D8m3l1B7btfBpp2nNuFkw | https://www.youtube.com/channel/UC6D8m3l1B7btfBpp2nNuFkw |
| 18 | Erick Wendel                               | @ErickWendelAcademy            | UCh84012dEUE076wM2CVFN9A | https://www.youtube.com/channel/UCh84012dEUE076wM2CVFN9A |
| 19 | Expert Cursos                              | @ExpertCursos                  | UC-cKIIGsroQqpH91A7nQGgg | https://www.youtube.com/channel/UC-cKIIGsroQqpH91A7nQGgg |
| 20 | Filipe Deschamps                           | @FilipeDeschamps               | UCU5JicSrEM5A63jkJ2QvGYw | https://www.youtube.com/channel/UCU5JicSrEM5A63jkJ2QvGYw |
| 21 | Front Beginners                            | @FrontBeginners                | UCWox-4vjxlV11PjoK9dOxtg | https://www.youtube.com/channel/UCWox-4vjxlV11PjoK9dOxtg |
| 22 | Hashtag Programação                        | @HashtagProgramacao            | UCafFexaRoRylOKdzGBU6Pgg | https://www.youtube.com/channel/UCafFexaRoRylOKdzGBU6Pgg |
| 23 | Ignorância Zero                            | @IgnorânciaZero                | UCmjj41YfcaCpZIkU-oqVIIw | https://www.youtube.com/channel/UCmjj41YfcaCpZIkU-oqVIIw |
| 24 | Daniel Morais Infocotidiano                | @infocotidiano                 | UCzSoG5woURgXNNaDjdm6f4Q | https://www.youtube.com/channel/UCzSoG5woURgXNNaDjdm6f4Q |
| 25 | Prof Izaias Neri                           | @izaiasneri                    | UCuo3X1pDWdaAf5R3Mr3lboA | https://www.youtube.com/channel/UCuo3X1pDWdaAf5R3Mr3lboA |
| 26 | Alex - JDev Treinamento on-line            | @Javaavancado                  | UCfZokasaM2WVd7OM07pnktQ | https://www.youtube.com/channel/UCfZokasaM2WVd7OM07pnktQ |
| 27 | Jogos & Programação                        | @jogosProgramEletronica        | UC1ESKyw2NK_T0KDsw9N_UJQ | https://www.youtube.com/channel/UC1ESKyw2NK_T0KDsw9N_UJQ |
| 28 | JULIO BATTISTI - LIVROS E CURSOS LTDA.     | @JulioBattistiAutor            | UC2JcJxc7H_MQDNyPu0QicWg | https://www.youtube.com/channel/UC2JcJxc7H_MQDNyPu0QicWg |
| 29 | Lucas Montano                              | @LucasMontano                  | UCyHOBY6IDZF9zOKJPou2Rgg | https://www.youtube.com/channel/UCyHOBY6IDZF9zOKJPou2Rgg |
| 30 | Matheus Battisti - Hora de Codar           | @MatheusBattisti               | UCDoFiMhpOnLFq1uG4RL4xag | https://www.youtube.com/channel/UCDoFiMhpOnLFq1uG4RL4xag |
| 31 | Neri Neitzke                               | @nerineitzke                   | UCKkrTv9Z34NvIg7onhD7oVA | https://www.youtube.com/channel/UCKkrTv9Z34NvIg7onhD7oVA |
| 32 | Otávio Miranda                             | @OtávioMiranda                 | UCORZcu08VQiRCKpVGHTWwAA | https://www.youtube.com/channel/UCORZcu08VQiRCKpVGHTWwAA |
| 33 | Programação Dinâmica                       | @pgdinamica                    | UC70mr11REaCqgKke7DPJoLg | https://www.youtube.com/channel/UC70mr11REaCqgKke7DPJoLg |
| 34 | Popularizando o Mundo da Programação       | @Portugol                      | UC5xuGX6JurlFWhnxCilKhDQ | https://www.youtube.com/channel/UC5xuGX6JurlFWhnxCilKhDQ |
| 35 | Professor Edson Maia                       | @ProfessorEdsonMaia            | UCN-wFj5TQDNMjQZEOp2RNfA | https://www.youtube.com/channel/UCN-wFj5TQDNMjQZEOp2RNfA |
| 36 | Professor MarcoMaddo                       | @ProfessorMarcoMaddo           | UCEBieECyJD82RNCmAAmw77A | https://www.youtube.com/channel/UCEBieECyJD82RNCmAAmw77A |
| 37 | Programação Popular                        | @programacaopopular            | UCsXyoSkpyZB741fkBKeEovQ | https://www.youtube.com/channel/UCsXyoSkpyZB741fkBKeEovQ |
| 38 | Programação Web                            | @programacaoweb                | UCwAa6VoM1GCg7n4s3u9FTAg | https://www.youtube.com/channel/UCwAa6VoM1GCg7n4s3u9FTAg |
| 39 | Programador BR                             | @Programadorbr                 | UCrdgeUeCll2QKmqmihIgKBQ | https://www.youtube.com/channel/UCrdgeUeCll2QKmqmihIgKBQ |
| 40 | Programe seu futuro                        | @programeseufuturo             | UC9XRXKkGgCXQ2oDbjI7JEBg | https://www.youtube.com/channel/UC9XRXKkGgCXQ2oDbjI7JEBg |
| 41 | QSP Tecnologia                             | @qsptecnologia                 | UCwAZmblPpmgOcWPLtVxvwBA | https://www.youtube.com/channel/UCwAZmblPpmgOcWPLtVxvwBA |
| 42 | RBtech                                     | @RBtechinfo                    | UCVEa_x1n5FwWrxH00MrDPzQ | https://www.youtube.com/channel/UCVEa_x1n5FwWrxH00MrDPzQ |
| 43 | Rocketseat                                 | @rocketseat                    | UCSfwM5u0Kce6Cce8_S72olg | https://www.youtube.com/channel/UCSfwM5u0Kce6Cce8_S72olg |
| 44 | Roger Melo \| JavaScript                   | @RogerMelo                     | UCmjDevp9Y8r-qi-xueD3Izg | https://www.youtube.com/channel/UCmjDevp9Y8r-qi-xueD3Izg |
| 45 | SatellaSoft                                | @SatellaSoft                   | UCBbMl4vZDvArxHrWoPtg_cw | https://www.youtube.com/channel/UCBbMl4vZDvArxHrWoPtg_cw |
| 46 | Thales Veloso                              | @thaleco.veloso                | UC9WucW7_3HiejAY3Y9L80oQ | https://www.youtube.com/channel/UC9WucW7_3HiejAY3Y9L80oQ |
| 47 | Tiago Aguiar                               | @TiagoAguiar                   | UCrWWMZ6GVOM5zqYAUI44XXg | https://www.youtube.com/channel/UCrWWMZ6GVOM5zqYAUI44XXg |
| 48 | Tiago Matos                                | @tiagomatosweb                 | UCXUWGUoYNwtRxaRPoB4KocA | https://www.youtube.com/channel/UCXUWGUoYNwtRxaRPoB4KocA |
| 49 | Danilo Aparecido - Torne-se um programador | @torneseumprogramador          | UCSxG4RK76hZG6HfACtgl-pg | https://www.youtube.com/channel/UCSxG4RK76hZG6HfACtgl-pg |

---

### 2. Expansão da rede com YouTube Data Tools

Os IDs dos canais iniciais foram inseridos no módulo "Channel Network" (https://ytdt.digitalmethods.net/mod_channels_net.php) da ferramenta YouTube Data Tools para a geração da rede de canais conectados.

A rede é salva em formato .gdf que é processado para extração dos IDs dos canais. Após isso os IDs são submetidos ao módulo "Channel List" para extração dos metadados dos canais.

In [1]:
# EXTRAIR OS IDS DOS CANAIS DO ARQUIVO GDF E SALVAR EM TXT E CSV

import os
import re
import pandas as pd

regex_patern = re.compile(r'UC[\w-]{22}')

input_files = [
	os.path.join(os.getcwd(), 'channelnet_seeds49_nodes55019_2025_12_30-01_59_15.gdf'),
	os.path.join(os.getcwd(), 'channelnet_seeds49_nodes1739_2025_12_29-12_11_22.gdf')
]

channel_ids = []
for input_file in input_files:
    with open(input_file, 'r', encoding='utf-8') as file:
        lines = file.readlines()
    for line in lines:
        matches = regex_patern.findall(line)
        channel_ids.extend(matches)
channel_ids = list(set(channel_ids))
print(f'Foram encontrados {len(channel_ids)} canais únicos no arquivo GDF.')

df_channels = pd.DataFrame(channel_ids, columns=['channel_id'])
output_csv = os.path.join(os.getcwd(), 'channel_ids.csv')
df_channels.to_csv(output_csv, index=False)

output_txt = os.path.join(os.getcwd(), 'channel_ids.txt')
with open(output_txt, 'w', encoding='utf-8') as file:
    file.write(','.join(channel_ids))

Foram encontrados 55022 canais únicos no arquivo GDF.

Com os IDs exportados, são coletados os metadados dos canais, utilizando o módulo "Channel List" do YouTube Data Tools (https://ytdt.digitalmethods.net/mod_channels_list.php), obtendo o arquivo:

 - channelsearch_channels55022_2025_12_30-12_11_01.csv

---

### 3. Pesquisa pelo termos referentes a programação no módulo "Channel List" do YouTube Data Tools (https://ytdt.digitalmethods.net/mod_channels_list.php) com os parâmetros:
 - reference language = PT
 - region code = BR
 - iterations = 10
 - rank by = relevance

TERMOS DE BUSCA:

- programação;
- programming;
- Python;
- Java;
- JavaScript;
- C/C++;
- C#

Fontes das 5 linguagens mais usadas:
- https://www.tiobe.com/tiobe-index/
- https://pypl.github.io/PYPL.html
- https://github.blog/news-insights/octoverse/octoverse-2024/

Linguagens: Python, Java, JavaScript, C/C++, C#

Resultados exportados em formato csv, incluindo os metadados dos canais.

Arquivos:

 - "[programação]channelsearch_channels396_2025_12_29-11_01_21.csv";
 - "[programming]channelsearch_channels498_2025_12_29-11_04_11.csv";
 - "[Python]channelsearch_channels480_2025_12_29-11_05_14.csv";
 - "[Java]channelsearch_channels459_2025_12_29-11_06_10.csv";
 - "[JavaScript]channelsearch_channels224_2025_12_29-11_06_55.csv";
 - "[C_C++]channelsearch_channels496_2025_12_29-11_08_32.csv";
 - "[C#]channelsearch_channels203_2025_12_29-11_09_28.csv".

---

### 4. Processamento dos arquivos obtidos pela pesquisa

In [2]:
# Juntar os arquivos e eliminar os duplicados

import os
import pandas as pd

buscas_arquivos = {
	'programação': '[programação]channelsearch_channels396_2025_12_29-11_01_21.csv',
	'programming': '[programming]channelsearch_channels498_2025_12_29-11_04_11.csv',
	'Python' : '[Python]channelsearch_channels480_2025_12_29-11_05_14.csv',
	'Java' : '[Java]channelsearch_channels459_2025_12_29-11_06_10.csv',
	'JavaScript' : '[JavaScript]channelsearch_channels224_2025_12_29-11_06_55.csv',
	'C/C++' : '[C_C++]channelsearch_channels496_2025_12_29-11_08_32.csv',
	'C#' : '[C#]channelsearch_channels203_2025_12_29-11_09_28.csv',
	'TODOS_DA_REDE' : 'channelsearch_channels55022_2025_12_30-12_11_01.csv'
}

# Criar dataframe com os arquivos CSV e adicionar coluna 'busca'
df = pd.DataFrame()
for busca, arquivo in buscas_arquivos.items():
	df_temp = pd.read_csv(os.path.join(os.getcwd(), arquivo), sep=',', encoding='utf-8')
	df_temp['busca'] = busca
	df = pd.concat([df, df_temp], ignore_index=True)

print(f'Quantidade de canais encontrados: {len(df)}')

# Remover linhas duplicadas com base no id do canal
df.drop_duplicates(subset=['id'], inplace=True)
df.reset_index(drop=True, inplace=True)

print(f'Quantidade de canais após remoção de duplicados: {len(df)}')

Quantidade de canais encontrados: 57778
Quantidade de canais após remoção de duplicados: 57671

---

### 5. Aplicação dos critérios para seleção dos canais mais relevantes:
- Canais que possuem a palavra programação na descrição;
- Canais com mais de 10 mil inscritos, mais de 1 milhão de visualizações e mais de 450 vídeos;
- Canais que possuem país definido;
- Canais Brasileiros;

Arquivo salvo em formato JSON

In [3]:
# FUNÇÃO PARA OBTER O ARROBA DOS CANAIS

import requests
from bs4 import BeautifulSoup
import json

def get_channel_info(channel_id):
	url = f"https://www.youtube.com/channel/{channel_id}/about"
	response = requests.get(url)
	response.raise_for_status()
	if response.status_code == 200:
		soup = BeautifulSoup(response.content, 'html.parser')
		try:
			script_ytInitialData = soup.find(lambda tag: tag.name == 'script' and 'var ytInitialData = ' in tag.text).text.split('var ytInitialData = ')[1].rstrip(';')
			json_data = json.loads(script_ytInitialData)
			arroba = json_data.get('metadata', {}).get('channelMetadataRenderer', {}).get('vanityChannelUrl', None).split('/')[-1] if json_data.get('metadata', {}).get('channelMetadataRenderer', {}).get('vanityChannelUrl', None) else None
			return arroba
		except Exception as err:
			print(f'Erro ao extrair script_ytInitialData: {err}')
			return None

In [4]:
# APLICAR OS CRITÉRIOS DE INCLUSÃO

dados = df.copy()

dados = dados[dados['description'].notnull()] # Filtrar canais que possuem descrição
dados = dados[dados['description'].str.contains(r'(?<!\w)(?:programação|programming|coding|dev|python|java|javascript|c|c\/c\+\+|c\+\+|c#|csharp)(?!\w)', case=False, regex=True)] # Filtrar canais que possuem as palavras listadas programação na descrição
canais_filtrados = dados[(dados['viewCount'] > 1000000) & (dados['subscriberCount'] > 7000) & (dados['videoCount'] > 250)] # Filtrar canais com mais de 1 milhão de visualizações, 7 mil inscritos e 250 vídeos
canais_filtrados = canais_filtrados[canais_filtrados['country'] == 'BR'] # Filtrar canais brasileiros
canais_filtrados = canais_filtrados.sort_values(by=['viewCount', 'subscriberCount', 'videoCount'], ascending=False) # Ordenar canais
canais_filtrados['url'] = 'https://www.youtube.com/channel/' + canais_filtrados['id'] # Adicionar coluna com o link do canal
canais_filtrados['arroba'] = canais_filtrados['id'].apply(get_channel_info) # Adicionar coluna com o arroba do canal

canais_filtrados = canais_filtrados[[
    "id",
    "title",
    "arroba",
    "country",
    "description",
    "keywords",
    "viewCount",
    "subscriberCount",
    "videoCount",
    "url"
]]

print(f"Total de canais filtrados: {len(canais_filtrados)}")

canais_filtrados.to_json('canais_filtrados_DataTools.json', orient='records', force_ascii=False, indent=4)
canais_filtrados

Total de canais filtrados: 263

,id,title,arroba,country,description,keywords,viewCount,subscriberCount,videoCount,url
35407,UCvdwhh_fDyWccR42-rReZLw,CNN Brasil,@CNNbrasil,BR,"Pense bem, pense CNN. Acompanhe nossos conteúd...",cnnbrasil|william waack|carol nogueira|notícia...,4.555693e+09,6470000.0,156937.0,https://www.youtube.com/channel/UCvdwhh_fDyWcc...
32426,UCR3TOnFWDeAlT-Ho6LueDmg,SBT,@sbt,BR,Este é o canal oficial do SBT no YouTube! Aqui...,SBT|Chaves|Programas|íntegra|destaques|entrevi...,4.424454e+09,13800000.0,29257.0,https://www.youtube.com/channel/UCR3TOnFWDeAlT...
51331,UCGVIctjzeX-ZoXgTphwJHWQ,Mundo Gloob,@MundoGloob,BR,"O meu canal é um mundo inspirador, perfeito pa...",Gloob|miraculous|infantil|crianças|dpa|ladybug...,4.068143e+09,8320000.0,5783.0,https://www.youtube.com/channel/UCGVIctjzeX-Zo...
23121,UCEPRQVF6hxGGM9gi1ELaWHg,TV Globo,@tvglobo,BR,Canal oficial da TV Globo no YouTube. Aqui voc...,Globo|Esporte|Jornalismo|Novelas|Séries|Trecho...,3.673573e+09,7000000.0,28519.0,https://www.youtube.com/channel/UCEPRQVF6hxGGM...
34174,UCPN_tMDcDoQCxoP4fVkQAxw,Vivo,@Vivo,BR,"Aqui você encontra nossas campanhas, vídeos tu...",Vivo|celular|mobile|operadora|brasil|internet|...,2.097738e+09,3900000.0,1539.0,https://www.youtube.com/channel/UCPN_tMDcDoQCx...
...,...,...,...,...,...,...,...,...,...,...
5941,UC-Xa9J9-B4jBOoBNIHkMMKA,Téo Me Why,@teomewhy,BR,"Oi, eu sou o Téo Calvo, do canal Téo Me Why: e...",python|ensino|dados|iniciante|python do zero,1.101908e+06,44200.0,529.0,https://www.youtube.com/channel/UC-Xa9J9-B4jBO...
46657,UCvo99mtwpnJtKJqeu0lQvLA,Py4all,@py4allbr,BR,"Bem-vindo à Py4All, sua fonte para aprender Py...",PySide6|VBA|Python|PythonGui|Qt|QtDesigner|SAP...,1.077377e+06,12500.0,268.0,https://www.youtube.com/channel/UCvo99mtwpnJtK...
27218,UCaTiVclf7mD7Wzbbsm6gGOA,Joviano Silveira,@JovianoSilveira,BR,Automatize processos. Domine dados. Evolua na ...,#powerquery|#excel|#powerbi|#powerpivot|#lingu...,1.076719e+06,40600.0,407.0,https://www.youtube.com/channel/UCaTiVclf7mD7W...
17,UCR6BA5LA2abGWL77pX9un9w,Programação For Kids - Aulas de Programação,@ProgramacaoForKids,BR,O Programação for Kids ensina crianças e adole...,roblox|programação|criação de jogos|jogo para ...,1.024331e+06,7290.0,726.0,https://www.youtube.com/channel/UCR6BA5LA2abGW...
38874,UC7zd5W1fyWfCbMVGWGXB92A,Embarcadero do Brasil,@embarcaderodobrasil,BR,"Canal Oficial RAD Studio, Delphi e C++ Builder...",Delphi|C++ Builder|RAD Studio,1.018217e+06,12000.0,346.0,https://www.youtube.com/channel/UC7zd5W1fyWfCb...

### 6. Filtro manual

Após os processamentos, a lista de canais passa por um filtro feito manualmente para aplicar o critério qualitativo de permanência, resultando na lista de 80 canais.

In [6]:
# Criar tabela csv com os canais selecionados

with open('canais_selecionados_DataTools.json', 'r', encoding='utf-8') as file:
	selecao_canais_final = json.load(file)

tabela_csv = pd.DataFrame(selecao_canais_final)
tabela_csv = tabela_csv[['id', 'title', 'arroba', 'description', 'keywords', 'url']]
tabela_csv.to_csv('canais_selecionados_DataTools.csv', index=False)

tabela_csv

,id,title,arroba,description,keywords,url
0,UCBbMl4vZDvArxHrWoPtg_cw,SatellaSoft,@SatellaSoft,"Fala, Dev! 👋 Desde 2009, a SatellaSoft compart...",Tecnologia|programação|games|desenvolvimento|m...,https://www.youtube.com/channel/UCBbMl4vZDvArx...
1,UCzR2u5RWXWjUh7CwLSvbitA,Mario Souto - Dev Soutinho,@DevSoutinho,"Olá pessoas, eu sou Mario Souto e aqui você va...",alura|javascript|js|css|reactjs|dev soutinho|m...,https://www.youtube.com/channel/UCzR2u5RWXWjUh...
2,UC07JWf9A0B1scApbS1Te7Ww,DevPleno,@DevPleno,Dicas de carreira e tutoriais de programação p...,devpleno|desenvolvimento|de|software|desenvolv...,https://www.youtube.com/channel/UC07JWf9A0B1sc...
3,UCs8iGueAbWqIZK7MtUkIl0w,Renato Gava,@renatogava,Programador Sênior .NET Full Stack. Certificad...,coder|developer|ti|javascript|c#|desenvovilmen...,https://www.youtube.com/channel/UCs8iGueAbWqIZ...
4,UCrdgeUeCll2QKmqmihIgKBQ,Programador BR,@Programadorbr,O lugar certo para quem quer saber sobre progr...,Tecnologia|Programação|Javascript|Empreendedor...,https://www.youtube.com/channel/UCrdgeUeCll2QK...
...,...,...,...,...,...,...
75,UCSfwM5u0Kce6Cce8_S72olg,Rocketseat,@rocketseat,"Faaaala, Devs! 🚀 Bem-vindos ao canal da Rocket...",rocketseat|programação|javascript|react|react-...,https://www.youtube.com/channel/UCSfwM5u0Kce6C...
76,UC-cKIIGsroQqpH91A7nQGgg,Expert Cursos,@ExpertCursos,Aqui você encontra muito conteúdo sobre Engenh...,AutoCAD|excel|engenharia|arquitetura|obras|ske...,https://www.youtube.com/channel/UC-cKIIGsroQqp...
77,UCXUWGUoYNwtRxaRPoB4KocA,Tiago Matos,@tiagomatosweb,Cursos e dicas sobre programação web,vue.js|laravel|php|javascript|css|html,https://www.youtube.com/channel/UCXUWGUoYNwtRx...
78,UCU5vSFBBO_cp6ie0OG74b2g,Refatorando,@Refatorando,"Bem-vindos ao canal Refatorando! Muito prazer,...",Programação|Tecnologia|Cursos|Desenvolvimento|...,https://www.youtube.com/channel/UCU5vSFBBO_cp6...
79,UCR6BA5LA2abGWL77pX9un9w,Programação For Kids - Aulas de Programação,@ProgramacaoForKids,O Programação for Kids ensina crianças e adole...,roblox|programação|criação de jogos|jogo para ...,https://www.youtube.com/channel/UCR6BA5LA2abGW...

---